name: Verify changes

on: [pull_request]

jobs:
  verify:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: yarn install
        name: Install dependencies

      - run: yarn verify:bail
        name: Verify changes
